[supervisord]
nodaemon=true
loglevel=info

[program:xray]
command=/usr/local/bin/xray run -c /etc/xray.json
autostart=true
autorestart=true

[program:nginx]
command=/usr/local/openresty/bin/openresty -g 'daemon off;'
autostart=true
autorestart=true

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
