[supervisord]
nodaemon=true
loglevel=info

[program:xray]
command=/usr/local/bin/xray run -c /etc/xray.json
autostart=true
autorestart=true

[program:nginx]
command=/usr/local/openresty/bin/openresty -g 'daemon off;'
autostart=true
autorestart=true

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true

# SSLH — MAGIC SARAP
[program:sslh]
command=/usr/bin/sslh -f --listen 0.0.0.0:8080 --ssh 127.0.0.1:22 --http 127.0.0.1:80
autostart=true
autorestart=true
